---
- name: Setup Personal Home Folders
  hosts: dc
  become: true
  vars:
    student_list: "{{ lookup('file', 'students.txt').splitlines() }}"

  tasks:
    - name: Create the Home base directory
      file:
        path: /srv/samba/homes
        state: directory
        mode: '0755'

    - name: Create individual folders and set ownership
      file:
        path: "/srv/samba/homes/{{ item }}"
        state: directory
        owner: "{{ item }}"
        group: "domain users"
        mode: '0700' # Only the student can see their own folder
      loop: "{{ student_list }}"

    - name: Add Homes Share to smb.conf
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [homes]
              comment = User Home Directories
              browseable = no
              read only = no
              create mask = 0700
              directory mask = 0700
              valid users = %S
